apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: healthcare-stage3
spec:
  project: healthcare-stage3
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger
    targetRevision: 3.3.1
    helm:
      releaseName: jaeger
      values: |
        provisionDataStore:
          cassandra: false
          elasticsearch: false
        storage:
          type: memory
        query:
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

